use serde_json::{json, Value};
use tauri::{AppHandle, Emitter, State};

use crate::commands::chat_state::ensure_chat_session;
use crate::persistence::{with_store, with_store_mut};
use crate::runtime::append_session_checkpoint;
use crate::{
    append_session_transcript, build_placeholder_assistant_response, create_work_item,
    infer_protocol, invoke_chat_by_protocol, make_id, now_iso, payload_string, redclaw_root,
    resolve_manuscript_path, slug_from_relative_path, write_text_file, AppState, ChatMessageRecord,
    RedclawProjectRecord,
};

pub fn resolve_default_model_config(
    settings: &Value,
) -> Option<(String, String, Option<String>, String)> {
    if let Some(ai_sources_json) = payload_string(settings, "ai_sources_json") {
        if let Ok(items) = serde_json::from_str::<Vec<Value>>(&ai_sources_json) {
            let default_id = payload_string(settings, "default_ai_source_id");
            let selected = items
                .iter()
                .find(|item| {
                    item.get("id").and_then(|value| value.as_str()) == default_id.as_deref()
                })
                .or_else(|| items.first())?;
            let base_url = selected
                .get("baseURL")
                .and_then(|value| value.as_str())
                .unwrap_or("")
                .trim()
                .to_string();
            let api_key = selected
                .get("apiKey")
                .and_then(|value| value.as_str())
                .map(|value| value.to_string());
            let model_name = selected
                .get("model")
                .and_then(|value| value.as_str())
                .unwrap_or("")
                .trim()
                .to_string();
            let protocol = selected
                .get("protocol")
                .and_then(|value| value.as_str())
                .map(|value| value.to_string())
                .unwrap_or_else(|| infer_protocol(&base_url, None, None));
            if !base_url.is_empty() && !model_name.is_empty() {
                return Some((protocol, base_url, api_key, model_name));
            }
        }
    }

    let base_url = payload_string(settings, "api_endpoint").unwrap_or_default();
    let model_name = payload_string(settings, "model_name").unwrap_or_default();
    if base_url.trim().is_empty() || model_name.trim().is_empty() {
        return None;
    }
    let api_key = payload_string(settings, "api_key");
    let protocol = infer_protocol(&base_url, None, None);
    Some((protocol, base_url, api_key, model_name))
}

pub fn redclaw_session_id_for_space(space_id: &str) -> String {
    let context_id = format!("redclaw-singleton:{space_id}");
    format!(
        "context-session:redclaw:{}",
        slug_from_relative_path(&context_id)
    )
}

pub fn detect_redclaw_artifact_kind(prompt: &str, source_label: &str) -> &'static str {
    let lower = prompt.to_lowercase();
    if lower.contains("save-copy") || lower.contains("文案包") {
        "copy"
    } else if lower.contains("save-image") || lower.contains("配图") || lower.contains("封面") {
        "image"
    } else if lower.contains("save-retro") || lower.contains("复盘") {
        "retro"
    } else if source_label.contains("scheduled") || source_label.contains("long-cycle") {
        "automation"
    } else {
        "run"
    }
}

pub fn save_redclaw_outputs(
    state: &State<'_, AppState>,
    kind: &str,
    project_id: &str,
    session_id: &str,
    prompt: &str,
    response: &str,
    source_label: &str,
) -> Result<Vec<Value>, String> {
    let mut artifacts = Vec::new();
    let timestamp = now_iso();
    let slug = slug_from_relative_path(&format!("{project_id}-{source_label}-{timestamp}"));

    let run_path = redclaw_root(state)?.join("runs").join(format!("{slug}.md"));
    let run_body = format!(
        "# RedClaw Run\n\n- Project: {}\n- Source: {}\n- Session: {}\n- Time: {}\n\n## Prompt\n\n{}\n\n## Response\n\n{}\n",
        project_id, source_label, session_id, timestamp, prompt, response
    );
    write_text_file(&run_path, &run_body)?;
    artifacts.push(json!({
        "kind": "run-log",
        "path": run_path.display().to_string(),
        "label": "RedClaw run log",
    }));

    match kind {
        "copy" => {
            let manuscript_relative = format!("redclaw/{}.md", slug);
            let manuscript_path = resolve_manuscript_path(state, &manuscript_relative)?;
            let manuscript_body = format!(
                "# RedClaw Copy Package\n\n> Project: {}\n> Generated by: {}\n\n{}",
                project_id, source_label, response
            );
            write_text_file(&manuscript_path, &manuscript_body)?;
            artifacts.push(json!({
                "kind": "manuscript",
                "path": manuscript_path.display().to_string(),
                "relativePath": manuscript_relative,
                "label": "Copy package manuscript",
            }));
        }
        "retro" => {
            let retro_path = redclaw_root(state)?
                .join("retro")
                .join(format!("{slug}.md"));
            let retro_body = format!(
                "# RedClaw Retro\n\n> Project: {}\n> Generated by: {}\n\n{}",
                project_id, source_label, response
            );
            write_text_file(&retro_path, &retro_body)?;
            artifacts.push(json!({
                "kind": "retro",
                "path": retro_path.display().to_string(),
                "label": "Retro note",
            }));
        }
        "image" => {
            let prompt_path = redclaw_root(state)?
                .join("images")
                .join(format!("{slug}.md"));
            let prompt_body = format!(
                "# RedClaw Image Prompt Pack\n\n> Project: {}\n> Generated by: {}\n\n{}",
                project_id, source_label, response
            );
            write_text_file(&prompt_path, &prompt_body)?;
            artifacts.push(json!({
                "kind": "image-prompts",
                "path": prompt_path.display().to_string(),
                "label": "Image prompt pack",
            }));
        }
        _ => {}
    }

    Ok(artifacts)
}

pub fn execute_redclaw_run(
    app: &AppHandle,
    state: &State<'_, AppState>,
    prompt: String,
    project_id: Option<String>,
    source_label: &str,
) -> Result<Value, String> {
    let settings_snapshot = with_store(state, |store| Ok(store.settings.clone()))?;
    let active_space_id = with_store(state, |store| Ok(store.active_space_id.clone()))?;
    let session_id = redclaw_session_id_for_space(&active_space_id);

    let response = if let Some((protocol, base_url, api_key, model_name)) =
        resolve_default_model_config(&settings_snapshot)
    {
        invoke_chat_by_protocol(
            &protocol,
            &base_url,
            api_key.as_deref(),
            &model_name,
            &prompt,
        )
        .unwrap_or_else(|_| build_placeholder_assistant_response(&prompt))
    } else {
        build_placeholder_assistant_response(&prompt)
    };

    let target_project_id = with_store(state, |store| {
        Ok(project_id.unwrap_or_else(|| {
            store
                .redclaw_state
                .projects
                .first()
                .map(|item| item.id.clone())
                .unwrap_or_else(|| make_id("redclaw-project"))
        }))
    })?;
    let artifact_kind = detect_redclaw_artifact_kind(&prompt, source_label);
    let artifacts = save_redclaw_outputs(
        state,
        artifact_kind,
        &target_project_id,
        &session_id,
        &prompt,
        &response,
        source_label,
    )?;

    with_store_mut(state, |store| {
        let (session, _) = ensure_chat_session(
            &mut store.chat_sessions,
            Some(session_id.clone()),
            Some("RedClaw".to_string()),
        );
        session.updated_at = now_iso();

        store.chat_messages.push(ChatMessageRecord {
            id: make_id("message"),
            session_id: session_id.clone(),
            role: "user".to_string(),
            content: prompt.clone(),
            display_content: None,
            attachment: None,
            created_at: now_iso(),
        });
        store.chat_messages.push(ChatMessageRecord {
            id: make_id("message"),
            session_id: session_id.clone(),
            role: "assistant".to_string(),
            content: response.clone(),
            display_content: None,
            attachment: None,
            created_at: now_iso(),
        });
        append_session_transcript(
            store,
            &session_id,
            "message",
            "user",
            prompt.clone(),
            Some(json!({ "source": source_label })),
        );
        append_session_transcript(
            store,
            &session_id,
            "message",
            "assistant",
            response.clone(),
            Some(json!({ "source": source_label })),
        );
        append_session_checkpoint(
            store,
            &session_id,
            "redclaw-run",
            format!("RedClaw completed {source_label}"),
            Some(json!({
                "responsePreview": response.chars().take(120).collect::<String>(),
                "artifactKind": artifact_kind,
                "artifacts": artifacts,
            })),
        );

        if let Some(project) = store
            .redclaw_state
            .projects
            .iter_mut()
            .find(|item| item.id == target_project_id)
        {
            project.updated_at = now_iso();
            project.status = "active".to_string();
            if project.goal.trim().is_empty() {
                project.goal = prompt.chars().take(160).collect();
            }
        } else {
            store.redclaw_state.projects.push(RedclawProjectRecord {
                id: target_project_id.clone(),
                goal: prompt.chars().take(160).collect(),
                platform: Some("generic".to_string()),
                task_type: Some("manual".to_string()),
                status: "active".to_string(),
                updated_at: now_iso(),
            });
        }

        store.work_items.push(create_work_item(
            "automation",
            format!("RedClaw {}", source_label),
            Some("Rust host executed a RedClaw run.".to_string()),
            Some(prompt.clone()),
            Some(json!({
                "projectId": target_project_id,
                "sessionId": session_id,
                "source": source_label,
                "artifactKind": artifact_kind,
                "artifacts": artifacts,
            })),
            2,
        ));

        Ok(())
    })?;

    let _ = app.emit(
        "redclaw:runner-message",
        json!({
            "sessionId": session_id.clone(),
            "artifactKind": artifact_kind,
            "artifacts": artifacts,
        }),
    );
    Ok(json!({
        "success": true,
        "sessionId": session_id,
        "response": response,
        "artifactKind": artifact_kind,
        "artifacts": artifacts
    }))
}
