use serde_json::{json, Value};
use tauri::{AppHandle, Emitter, State};

use crate::agent::{execute_prepared_session_agent_turn, PreparedSessionAgentTurn, RedclawRunTurn};
use crate::persistence::{with_store, with_store_mut};
use crate::{
    create_work_item, make_id, now_iso, redclaw_root, resolve_manuscript_path,
    slug_from_relative_path, write_text_file, AppState, RedclawProjectRecord,
};

pub fn redclaw_session_id_for_space(space_id: &str) -> String {
    let context_id = format!("redclaw-singleton:{space_id}");
    format!(
        "context-session:redclaw:{}",
        slug_from_relative_path(&context_id)
    )
}

pub fn detect_redclaw_artifact_kind(prompt: &str, source_label: &str) -> &'static str {
    let lower = prompt.to_lowercase();
    if lower.contains("save-copy") || lower.contains("文案包") {
        "copy"
    } else if lower.contains("save-image") || lower.contains("配图") || lower.contains("封面") {
        "image"
    } else if lower.contains("save-retro") || lower.contains("复盘") {
        "retro"
    } else if source_label.contains("scheduled") || source_label.contains("long-cycle") {
        "automation"
    } else {
        "run"
    }
}

pub fn save_redclaw_outputs(
    state: &State<'_, AppState>,
    kind: &str,
    project_id: &str,
    session_id: &str,
    prompt: &str,
    response: &str,
    source_label: &str,
) -> Result<Vec<Value>, String> {
    let mut artifacts = Vec::new();
    let timestamp = now_iso();
    let slug = slug_from_relative_path(&format!("{project_id}-{source_label}-{timestamp}"));

    let run_path = redclaw_root(state)?.join("runs").join(format!("{slug}.md"));
    let run_body = format!(
        "# RedClaw Run\n\n- Project: {}\n- Source: {}\n- Session: {}\n- Time: {}\n\n## Prompt\n\n{}\n\n## Response\n\n{}\n",
        project_id, source_label, session_id, timestamp, prompt, response
    );
    write_text_file(&run_path, &run_body)?;
    artifacts.push(json!({
        "kind": "run-log",
        "path": run_path.display().to_string(),
        "label": "RedClaw run log",
    }));

    match kind {
        "copy" => {
            let manuscript_relative = format!("redclaw/{}.md", slug);
            let manuscript_path = resolve_manuscript_path(state, &manuscript_relative)?;
            let manuscript_body = format!(
                "# RedClaw Copy Package\n\n> Project: {}\n> Generated by: {}\n\n{}",
                project_id, source_label, response
            );
            write_text_file(&manuscript_path, &manuscript_body)?;
            artifacts.push(json!({
                "kind": "manuscript",
                "path": manuscript_path.display().to_string(),
                "relativePath": manuscript_relative,
                "label": "Copy package manuscript",
            }));
        }
        "retro" => {
            let retro_path = redclaw_root(state)?
                .join("retro")
                .join(format!("{slug}.md"));
            let retro_body = format!(
                "# RedClaw Retro\n\n> Project: {}\n> Generated by: {}\n\n{}",
                project_id, source_label, response
            );
            write_text_file(&retro_path, &retro_body)?;
            artifacts.push(json!({
                "kind": "retro",
                "path": retro_path.display().to_string(),
                "label": "Retro note",
            }));
        }
        "image" => {
            let prompt_path = redclaw_root(state)?
                .join("images")
                .join(format!("{slug}.md"));
            let prompt_body = format!(
                "# RedClaw Image Prompt Pack\n\n> Project: {}\n> Generated by: {}\n\n{}",
                project_id, source_label, response
            );
            write_text_file(&prompt_path, &prompt_body)?;
            artifacts.push(json!({
                "kind": "image-prompts",
                "path": prompt_path.display().to_string(),
                "label": "Image prompt pack",
            }));
        }
        _ => {}
    }

    Ok(artifacts)
}

pub fn execute_redclaw_run(
    app: &AppHandle,
    state: &State<'_, AppState>,
    prompt: String,
    project_id: Option<String>,
    source_label: &str,
) -> Result<Value, String> {
    let active_space_id = with_store(state, |store| Ok(store.active_space_id.clone()))?;
    let session_id = redclaw_session_id_for_space(&active_space_id);
    let turn = PreparedSessionAgentTurn::redclaw_run(RedclawRunTurn::new(
        source_label,
        session_id.clone(),
        prompt.clone(),
    ));
    let execution = execute_prepared_session_agent_turn(Some(app), state, &turn)?;

    let target_project_id = with_store(state, |store| {
        Ok(project_id.unwrap_or_else(|| {
            store
                .redclaw_state
                .projects
                .first()
                .map(|item| item.id.clone())
                .unwrap_or_else(|| make_id("redclaw-project"))
        }))
    })?;
    let artifact_kind = detect_redclaw_artifact_kind(&prompt, source_label);
    let artifacts = save_redclaw_outputs(
        state,
        artifact_kind,
        &target_project_id,
        &session_id,
        &prompt,
        execution.response(),
        source_label,
    )?;

    with_store_mut(state, |store| {
        if let Some(project) = store
            .redclaw_state
            .projects
            .iter_mut()
            .find(|item| item.id == target_project_id)
        {
            project.updated_at = now_iso();
            project.status = "active".to_string();
            if project.goal.trim().is_empty() {
                project.goal = prompt.chars().take(160).collect();
            }
        } else {
            store.redclaw_state.projects.push(RedclawProjectRecord {
                id: target_project_id.clone(),
                goal: prompt.chars().take(160).collect(),
                platform: Some("generic".to_string()),
                task_type: Some("manual".to_string()),
                status: "active".to_string(),
                updated_at: now_iso(),
            });
        }

        store.work_items.push(create_work_item(
            "automation",
            format!("RedClaw {}", source_label),
            Some("Rust host executed a RedClaw run.".to_string()),
            Some(prompt.clone()),
            Some(json!({
                "projectId": target_project_id,
                "sessionId": execution.session_id(),
                "source": source_label,
                "artifactKind": artifact_kind,
                "artifacts": artifacts,
            })),
            2,
        ));

        Ok(())
    })?;

    let _ = app.emit(
        "redclaw:runner-message",
        json!({
            "sessionId": execution.session_id(),
            "artifactKind": artifact_kind,
            "artifacts": artifacts,
        }),
    );
    Ok(json!({
        "success": true,
        "sessionId": execution.session_id(),
        "response": execution.response(),
        "artifactKind": artifact_kind,
        "artifacts": artifacts
    }))
}
